services:
  nginx:
    image: nginx:1.25
    ports:
      - "1243:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - vita
    healthcheck:
      test: ["CMD", "curl", "-f", "http://php:9000"]
      interval: 10s
      timeout: 5s
      retries: 3

  php:
    image: php:7.4-fpm
    working_dir: /var/local/sandboxes/dev/www
    volumes:
      - .:/var/local/sandboxes/dev/www
    environment:
      PHP_FPM_LISTEN: "0.0.0.0:9000"
    networks:
      - vita
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm"]
      interval: 10s
      timeout: 5s
      retries: 3
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: vite_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vita


networks:
  vita:
    driver: bridge

volumes:
  postgres_data:
